# Author:  Joe Harrison
# This is a GitHub Actions workflow that uses Terraform to deploy a vSphere Windows Server 2016 VM. 
# It will generate a main.tf file based on user input, in the root of the repository and then apply the Terraform configuration to create the VM. 
# If the Terraform apply fails, it will initiate a cleanup by destroying the resources created.

# Name of the workflow
name: 'vSphere WS16 CD'

# Define environment variables
env:
  # vSphere password used for authentication
  TF_VAR_vsphere_password: ${{ secrets.VSPHERE_PASSWORD }}
  # SSH password used for authentication
  TF_VAR_ssh_password: ${{ secrets.SSH_PASSWORD }}  

# Define the events that trigger the workflow
on:
  # Trigger the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Enter desired hostname, vCenter IP, vCenter User, separated by commas i.e. "windows-box-01,192.168.1.150,admin@domain.local"'
        required: true
      vsphere_cluster:
        description: 'Enter the name of the vSphere cluster to deploy to'
        required: true
      vsphere_folder:
        description: 'Enter the path of the existing folder to deploy to i.e. "Path/To/VM"'
        required: true
      vsphere_datastore:
        description: 'Enter the vSphere datacenter and datastore to deploy to, separated by commas i.e. "DATACENTER1,DATASTORE_NAME"'
        required: true
      vsphere_network:
        description: 'Enter the vSphere port group connect the VM to'
        required: true
      network_details:
        description: 'Enter ip address, network subnet cidr, and network gateway for the port group, separated by commas i.e. "192.168.1.10,24,192.168.1.1"'
        required: true
      dns_servers:
        description: 'Enter DNS server addresses to be used, separated by commas i.e. "192.168.1.100,192.168.1.200". Leave Blank to use Cloudflare DNS'
        required: false
      cpu_ram:
        description: 'Enter the number of CPUs and the amount of RAM (MB) to allocate to the vm, separated by a comma i.e. "4,8192"'
        required: true
      AD_Details:
        description: 'Enter ADJoin, ADPass, ADOU, ADUser, and ADDomain, separated by commas i.e. "true,password,username,domain.local". Leave empty if no domain join is required.'
        required: false
      vm_disks:
        description: 'Enter the size of each additional disk to add in GB, separated by commas. For example: "100,200". Leave empty if no additional disks are needed.'
        required: false

# Define permissions for this workflow
permissions:
  contents: read

# Define jobs in this workflow  
jobs:
  # Define a job for main.tf file actions
  generate-main-tf:
    name: 'Terraform vSphere Windows Server 2016 main.tf Generation'
    runs-on: [self-hosted, devops]
    environment: production

    steps:
      # Checkout the repository to the GitHub Actions runner 
      - name: Checkout
        uses: actions/checkout@v4  

      # If main.tf does not exist, we generate a new one using user input
      - name: Check if main.tf exists
        run: |
          if [ -f "main.tf" ]; then
            echo "main.tf already exists, skipping file generation."
            echo "file_exists=true" >> $GITHUB_ENV      
          else
            echo "main.tf does not exist, continuing with file generation."
            echo "file_exists=false" >> $GITHUB_ENV
          fi
        id: check-main-tf
      
      - name: Generate main.tf with user input
        if: env.file_exists == 'false'
        run: |
          # It parses various input parameters and generates the main.tf file using them
          # If any optional parameters are not provided, it handles them gracefully
          
          # Using the Internal Field Separator (IFS) variable, parse the input strings into individual variables
          IFS=',' read -r hostname vsphere_ip vsphere_user <<< "${{ github.event.inputs.hostname }}"
          IFS=',' read -r vsphere_datacenter vsphere_datastore <<< "${{ github.event.inputs.vsphere_datastore }}"
          IFS=',' read -r vm_ip vm_netmask vm_gateway <<< "${{ github.event.inputs.network_details }}"
          # Similarly, parse the CPU and memory details string into individual variables
          IFS=',' read -r num_cpus memory <<< "${{ github.event.inputs.cpu_ram }}"
          # Remove leading and trailing whitespace from the Active Directory details string
          trimmed_ad_details=$(echo "${{ github.event.inputs.AD_Details }}" | xargs)
          # Initialize an empty string for the AD details
          ad_details_str=""
          # If the AD details string is not empty, parse it into individual variables and build the details string
          if [ ! -z "${trimmed_ad_details}" ]; then
            IFS=',' read -r ADJoin ADPass ADOU ADUser ADDomain <<< "${trimmed_ad_details}"
            ad_details_str=$'ADJoin         = '${ADJoin}$'\n     ADPass         = "'${ADPass}$'"\n     ADOU           = "'${ADOU}$'"\n     ADUser         = "'${ADUser}$'"\n     ADDomain       = "'${ADDomain}$'"\n     vm_dns_domain  = "'${ADDomain}$'"\n'
          else
            ad_details_str=$'ADJoin         = false\n     ADPass         = "'$'"\n     ADOU           = "'$'"\n     ADUser         = "'$'"\n     ADDomain       = "'$'"\n     vm_dns_domain  = "'$'"\n'
          fi
          # Remove leading and trailing whitespace from the disk details string
          trimmed_disks=$(echo "${{ github.event.inputs.vm_disks }}" | xargs)
          # If the disks string is not empty, parse it into an array and build the disks string
          if [ ! -z "${trimmed_disks}" ]; then
            IFS=',' read -ra disk_sizes <<< "${trimmed_disks}"
            for i in "${!disk_sizes[@]}"; do
              disks_str+="{ size = ${disk_sizes[i]}, thinprov = true, unit_number = $((i+1)) },"
            done
            disks_str=${disks_str%?}  # Removes the last character, which is the trailing comma
          fi
          # Initialize an empty string for the DNS servers
          dns_servers_str=""
          # Remove leading and trailing whitespace from the DNS servers string
          trimmed_dns_servers=$(echo "${{ github.event.inputs.dns_servers }}" | xargs)
          # If the DNS servers string is not empty, parse it into an array and build the DNS servers string
          if [ ! -z "${trimmed_dns_servers}" ]; then
            IFS=',' read -ra dns_servers <<< "${trimmed_dns_servers}"
            for dns_server in "${dns_servers[@]}"; do
              dns_servers_str+='"'"$dns_server"'",'
            done
            dns_servers_str=${dns_servers_str%?}  # Removes the last character, which is the trailing comma
            dns_servers_str="vm_dns_servers = [${dns_servers_str}]"
          else
            dns_servers_str='vm_dns_servers = ["1.1.1.1","1.0.0.1"]'
          fi

          cat > main.tf << EOF
          # Variables to be populated by GitHub Secrets at runtime
          # vCenter Password
          variable "vsphere_password" {}
          
          # VM Password
          variable "vm_password" {}
          
          # Define the required version of Terraform and the required vSphere and AWS provider version
          terraform {
            required_version = ">= 1.5.0"
            required_providers {
              vsphere = {
                source  = "hashicorp/vsphere"
                version = "2.6.1"
              }
              random = {
                source  = "hashicorp/random"
                version = ">= 3.6.0"
              }
              template = {
                source  = "hashicorp/template"
                version = ">= 2.2.0"
              }
            }
          }
          
          # Connection to vSphere environment
          provider "vsphere" {
            user                  = "$vsphere_user"
            password              = var.vsphere_password
            vsphere_server        = "$vsphere_ip"
            allow_unverified_ssl  = true
          }
          
          # Define the module source and its location
          module "vsphere-ws16" {
            source = "./modules/vsphere-ws-16"
          
            # Define vSphere Information 
            vsphere_config = {
              vcenter_server = "$vsphere_ip"
              user           = "$vsphere_user"
              datacenter     = "$vsphere_datacenter"
              cluster        = "${{ github.event.inputs.vsphere_cluster }}"
              datastore      = "$vsphere_datastore"
              vm_network     = "${{ github.event.inputs.vsphere_network }}"
              vm_folder      = "${{ github.event.inputs.vsphere_folder }}"
            }
                      
            // Define Host Information 
            ws16 = {
               // VM Hostname
               hostname            = "$hostname"
               vm_password         = var.vm_password
              
               // VM Specifications
               num_cpus            = "$num_cpus"
               memory              = "$memory"
               disk_size           = "150"
               vm_disks            = [ ${disks_str} ]
               vm_timezone         = "085"
               template            = "WS16-PKR-V1"           
               
               // Network Details
               vm_ip          = "$vm_ip"
               vm_netmask     = "$vm_netmask"               
               vm_gateway     = "$vm_gateway"
               ${dns_servers_str}
               
               // AD Details
               $ad_details_str
            }  

          }
          EOF

          # Print the generated main.tf
          cat main.tf

      # If a new main.tf file was created, this step commits and pushes it to the repository
      - name: Commit and push main.tf
        if: ${{ env.file_exists }} == 'false'
        run: |
          # It sets the git user name and email to 'GitHub Actions'
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          
          # It stages, commits, and pushes the new main.tf file
          git add main.tf
          git commit -m "Add generated main.tf"
          git push

  # Define a job for Terraform actions          
  terraform-vsphere-windows-server-2016-pipeline:
    name: 'Terraform vSphere Windows Server 2016 Pipeline'
    needs: generate-main-tf
    runs-on: [self-hosted, devops]
    environment: production

    steps:   
    # Checkout the repository to the GitHub Actions runner 
    - name: Checkout
      uses: actions/checkout@v4

    # Fetch the latest commit  
    - name: Fetch the latest commit
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/* --depth=1
        LATEST_COMMIT=$(git rev-parse origin/${GITHUB_REF##*/})
        git checkout $LATEST_COMMIT       
                
    # Setup Node.js environment with a specific version
    - name: Node Setup
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    # Setup Terraform CLI on the runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    # Initialise your Terraform working directory
    - name: Terraform Init
      run: terraform init

    # Generate an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
    
    # Apply the changes required to reach the desired state of the configuration
    - name: Terraform Apply
      id: apply    
      continue-on-error: true
      run: terraform apply -auto-approve

    # Check if Terraform Apply failed and set an output variable
    - name: Check Terraform Apply Outcome
      id: check
      run: echo "apply_failed=${{ steps.apply.outcome == 'failure' }}" >> $GITHUB_ENV

    # Destroy if Terraform Apply failed
    - name: Terraform Apply Failure Handler
      if: env.apply_failed == 'true'
      id: failure-handler
      run: |
        echo "Terraform Apply failed. Initiating cleanup..."
        terraform destroy -auto-approve
        echo "cleanup_done=true" >> $GITHUB_ENV              